spring:
  application:
    name: order-service
  profiles:
    default: dev
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        namespace: ${NACOS_NAMESPACE:dev}
    openfeign:
      client:
        config:
          default:
            connect-timeout: ${FEIGN_CONNECT_TIMEOUT:2000}
            read-timeout: ${FEIGN_READ_TIMEOUT:3000}
  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.wwweinuo.cloudmall.order
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
